version: '3'

services:

    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        container_name: "sat-bcb-pix"
        ports:
            - 8082:8082

    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        container_name: "sat-itau-erp"
        ports:
            - 9091:9091

    #Application database
    postgres:
        image: 'postgres:9.6-alpine'
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        container_name: "pix-km-postgres"
        ports:
            - 5433:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: key-manager

    pgadmin4:
        image: 'dpage/pgadmin4:5.5'
        volumes:
            - pgadmin-volume:/var/lib/pgadmin
        container_name: "pix-km-pgadmin4"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: pass123
        ports:
            - 8085:80

volumes:
    postgres-volume:
    pgadmin-volume: